default_platform(:ios)

platform :ios do
  before_all do
    Dotenv.load ".env"
    Dotenv.load ".env.ios"
  end

  desc "Update ci keychain"
  lane :update_keychain do
    create_keychain(
      name: "ci",
      password: "test",
      default_keychain: false,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    import_certificate(
      keychain_name: "ci",
      keychain_password: "test",
      certificate_path: File.absolute_path("certificate.p12"),
      certificate_password: ENV['FL_UNLOCK_KEYCHAIN_PASSWORD']
    )
  end

  desc "Sync signing"
  lane :signing do
    unlock_keychain(
      path: "ci", 
      password: ENV['FL_UNLOCK_KEYCHAIN_PASSWORD']
    )
    install_provisioning_profile
    update_code_signing_settings
  end
  
  desc "Build binary"
  lane :build do
    xcode_select ENV['FL_XCODE_PATH']
    
    signing
    
    build_ios_app(
      include_bitcode: false
    )
  end

  desc "Release binary"
  lane :release do

    increment_build_number
    build
    firebase_app_distribution

  end

  error do |lane, exception|
    
  end
end
